version: "3.8"
services:
  db:
    container_name: mysql_server
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_HOST_AUTH_METHOD: trust
    # volumes:   
    #   - ./volumeToAttach:/mysqldb
    #   # - ./var/lib/mysql-files:/var/lib/mysql-files/
    ports:
      - '3305:3305'
    networks:
      - network_ml

  sqlpad:
    container_name: mysqlpad_ml
    image: sqlpad/sqlpad:master
    depends_on:
      - db
    environment:
      SQLPAD_ADMIN: admin@sql.pad
      SQLPAD_ADMIN_PASSWORD: password123
    ports:
      - '3000:3000'
    # volumes:
    #   - ./ml_space:/sqlpad
    networks:
      - network_ml

networks:
  network_ml: